### ISSUE TITLE
[Request] Batch conversion of GMD to CSV

### ISSUE THREAD

**Issue by quiple** [Fusion86/Cirilla#31]
Hello!

It would be nice to be able to batch convert GMD to CSV multiple files at once.

I need this feature because I have to use machine translation.

**Comment by Fusion86** [comment]
Would you like to convert a whole folder, or just like 4 files at once?

If you want to convert all files inside the common/text folder you'll end up with 7.580 files. This doesn't really take long to convert, but idk if you want to be able to exclude certain files?

**Comment by quiple** [comment]
Either way doesn't matter, but the latter is what I was thinking of.

It would be nice to be able to select and convert only the files I want.

In addition, It should also be able to convert from CSV to GMD at once too.

**Comment by quiple** [comment]
In addition, It should also be able to convert from CSV to GMD at once.

**Comment by Fusion86** [comment]
Alright, I'll try to come up with something neat.

**Comment by Fusion86** [comment]
@quiple alright so I tried something.

### GMD to CSV

Make sure the correct mode is set.
Set the output directory to the folder where you want the CSV files to go.
Click add files or add folder to select the GMD files you want to convert.

I don't recommend using the add folder recursively option, because then you'll end up with duplicate files, this is because some files are duplicated in the `steam`, `trace`, or `vfont` folder. This tool wil NOT preserve the directory structure when exporting from GMD to CSV.

If all looks good click "Export all to GMD" to do exactly that.

### CSV to GMD

Make sure the correct mode is set.
Set the GMD source directory to wherever the game files are. These files will be used as the "base", all changes from the CSV will be applied to these files. The files in this directory will not be changed, the changed files will be saved to the "output directory".
Click add files or add folder to add your CSV files.

In the table you can see which CSV file uses which GMD as template, and where it will be saved (the target field).
If everything looks in order you can click "Apply all to GMD".

[Video I guess](https://youtu.be/EU-xc4XenSA)

Program download link (extract all and launch Cirilla.WPF)
[net5.0-windows.zip](https://github.com/Fusion86/Cirilla/files/7026288/net5.0-windows.zip) (maybe you need to right click the zip and check "Unblock" idk)

Please let me know whether this works for you, or which changes you'd like to see.

P.s. the tool currently can't see the difference between `armor_eng.gmd` and `steam/armor_eng.gmd`, so make sure to only use a 'flat' directory structure. This is also the reason why I recommend not using the "Add Folder Recursively" button.

P.s.s when using "CSV to GMD" mode the tool will only write GMD files that have changes, if you CSV is identical to your input GMD then there will be NO output GMD.

**Comment by quiple** [comment]
It works satisfactorily. Thank you!
